import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import { Roboto, Poppins, Comfortaa, Rajdhani } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const rajdhani = Rajdhani({
  weight: ['400', '700'],
  style: ['normal',],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rajdhani',
})


const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const poppins = Poppins({
  weight: ['400', '700', '200', '500', '100'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

const comfortaa = Comfortaa({
  weight: ['400', '700', '500', '600'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-comfortaa',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} ${comfortaa.variable} ${rajdhani.variable} comfortaa antialiased`}
      >
        <AuthProvider>
          {children}
          <Toaster />

        </AuthProvider>
      </body>
    </html>
  );
}
